name: praktikum
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.2
  get: ^4.6.6
  get_storage: ^2.1.1
  easy_stepper: ^0.8.1
  image_picker: ^1.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test: 
    sdk: flutter

flutter_native_splash: 
  color: '#3eb489'
  image: assets/images/splash.png

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/images/icon.png
  ios: false

flutter: 
  assets: 
    - assets/images/
  
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/Metropolis/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Metropolis/Metropolis-Bold.otf
          weight: 700

  uses-material-design: true

