name: praktikum
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.2
  get: ^4.6.6
  get_storage: ^2.1.1
  easy_stepper: ^0.8.1
  image_picker: ^1.0.4
  http: ^1.0.0
  camera: ^0.10.5+5
  image_cropper: ^5.0.0
  flutter_image_compress: ^2.1.0
  flutter_local_notifications: ^16.1.0
  webview_flutter: ^3.0.4
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  firebase_messaging: ^14.6.6
  shared_preferences: ^2.2.2
  appwrite: ^11.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test: 
    sdk: flutter
  mockito: ^5.4.3
  build_runner: ^2.4.7

flutter_native_splash: 
  color: '#3eb489'
  image: assets/images/splash.png

flutter_launcher_icons: 
  android: true
  image_path: assets/images/icon.png
  ios: false

flutter: 
  assets: 
    - assets/images/
  
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/Metropolis/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Metropolis/Metropolis-Bold.otf
          weight: 700

  uses-material-design: true

